In [119]:
import pandas as pd

In [120]:
def department_highest_salary(employee: pd.DataFrame, department: pd.DataFrame) -> pd.DataFrame:
    employee['departmentId'] = department['departmentId']

In [121]:
data = [[1, 'Joe', 70000, 1], [2, 'Jim', 90000, 1], [3, 'Henry', 80000, 2], [4, 'Sam', 60000, 2], [5, 'Max', 90000, 1]]
employee = pd.DataFrame(data, columns=['id', 'name', 'salary', 'departmentId']).astype({'id':'Int64', 'name':'object', 'salary':'Int64', 'departmentId':'Int64'})
data = [[1, 'IT'], [2, 'Sales']]
department = pd.DataFrame(data, columns=['id', 'name']).astype({'id':'Int64', 'name':'object'})

In [122]:
employee

   id   name  salary  departmentId
0   1    Joe   70000             1
1   2    Jim   90000             1
2   3  Henry   80000             2
3   4    Sam   60000             2
4   5    Max   90000             1

In [123]:
department

   id   name
0   1     IT
1   2  Sales

In [124]:
employee.groupby('departmentId')['salary'].transform('max')

0    90000
1    90000
2    80000
3    80000
4    90000
Name: salary, dtype: Int64

In [125]:
employee = employee[employee['salary'] == employee.groupby('departmentId')['salary'].transform('max')]
new = employee['name'].rename('Employee')
employee

   id   name  salary  departmentId
1   2    Jim   90000             1
2   3  Henry   80000             2
4   5    Max   90000             1

In [126]:
employee.sort_values(by='departmentId', ascending=False, inplace=True)
employee.sort_values(by='salary', ascending=False, inplace=True)
employee

/var/folders/ft/pkyxbgxd5qqcsz8hx6b9xk480000gn/T/ipykernel_9159/4148099871.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  employee.sort_values(by='departmentId', ascending=False, inplace=True)
/var/folders/ft/pkyxbgxd5qqcsz8hx6b9xk480000gn/T/ipykernel_9159/4148099871.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  employee.sort_values(by='salary', ascending=False, inplace=True)

   id   name  salary  departmentId
1   2    Jim   90000             1
4   5    Max   90000             1
2   3  Henry   80000             2

In [127]:
data = [[1, 'Joe', 70000, 1], [2, 'Jim', 90000, 1], [3, 'Henry', 80000, 2], [4, 'Sam', 60000, 2], [5, 'Max', 90000, 1]]
employee = pd.DataFrame(data, columns=['id', 'name', 'salary', 'departmentId']).astype({'id':'Int64', 'name':'object', 'salary':'Int64', 'departmentId':'Int64'})
data = [[1, 'IT'], [2, 'Sales']]
department = pd.DataFrame(data, columns=['id', 'name']).astype({'id':'Int64', 'name':'object'})

In [128]:
df = employee.merge(department, left_on='departmentId', right_on='id', suffixes=('', '_dept'))
df

   id   name  salary  departmentId  id_dept name_dept
0   1    Joe   70000             1        1        IT
1   2    Jim   90000             1        1        IT
2   3  Henry   80000             2        2     Sales
3   4    Sam   60000             2        2     Sales
4   5    Max   90000             1        1        IT

In [129]:
df = df[df['salary'] == df.groupby('departmentId')['salary'].transform('max')]
df

   id   name  salary  departmentId  id_dept name_dept
1   2    Jim   90000             1        1        IT
2   3  Henry   80000             2        2     Sales
4   5    Max   90000             1        1        IT

In [130]:
df = df[['name_dept', 'name', 'salary']].rename(columns={'name_dept': 'Department', 'name': 'Employee', 'salary': 'Salary'})
df

  Department Employee  Salary
1         IT      Jim   90000
2      Sales    Henry   80000
4         IT      Max   90000

In [138]:
import pandas as pd

def rising_temperature(weather: pd.DataFrame) -> pd.DataFrame:
    df = weather.sort_values(by = 'recordDate')
    df['yesterday'] = df['recordDate'].shift(1)
    df['check'] = df['recordDate'] == df['yesterday'] + pd.Timedelta(days=1)
    df = df[df['temperature'] > df['temperature'].shift(1)]
    df = df['id'].to_frame()
    return df

In [132]:
data = [[1, '2015-01-01', 10], [2, '2015-01-02', 25], [3, '2015-01-03', 20], [4, '2015-01-04', 30]]
weather = pd.DataFrame(data, columns=['id', 'recordDate', 'temperature']).astype({'id':'Int64', 'recordDate':'datetime64[ns]', 'temperature':'Int64'})

In [139]:
rising_temperature(weather)

   id
1   2
3   4