In [150]:
import pandas as pd

In [151]:
def find_investments(insurance: pd.DataFrame) -> pd.DataFrame:
    count = insurance['tiv_2015'].value_counts()
    count = count[count>1].index
    
    insurance = insurance[insurance['tiv_2015'].isin(count)]
    
    for i in count:
        print(insurance[insurance['tiv_2015']==i])
    return insurance

In [152]:
data = [[1, 10, 5, 10, 10], [2, 20, 20, 20, 20], [3, 10, 30, 20, 20], [4, 10, 40, 40, 40]]
insurance = pd.DataFrame(data, columns=['pid', 'tiv_2015', 'tiv_2016', 'lat', 'lon']).astype({'pid':'Int64', 'tiv_2015':'Float64', 'tiv_2016':'Float64', 'lat':'Float64', 'lon':'Float64'})

In [153]:
insurance

   pid  tiv_2015  tiv_2016   lat   lon
0    1      10.0       5.0  10.0  10.0
1    2      20.0      20.0  20.0  20.0
2    3      10.0      30.0  20.0  20.0
3    4      10.0      40.0  40.0  40.0

In [154]:
find_investments(insurance)

   pid  tiv_2015  tiv_2016   lat   lon
0    1      10.0       5.0  10.0  10.0
2    3      10.0      30.0  20.0  20.0
3    4      10.0      40.0  40.0  40.0

   pid  tiv_2015  tiv_2016   lat   lon
0    1      10.0       5.0  10.0  10.0
2    3      10.0      30.0  20.0  20.0
3    4      10.0      40.0  40.0  40.0